repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.83.5 
  hooks:
  - id: terraform_tflint

- repo: https://github.com/Yelp/detect-secrets
  rev: v1.4.0
  hooks:
  - id: detect-secrets
    args: ['--baseline', '.secrets.baseline']